version: '3.3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DB}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: tesladb
    volumes:
      - ./postgres:/var/lib/postgresql/data